apiVersion: v1
kind: Service
metadata:
  name: tenant-db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: {{- if .Values.global.useCloudSql }} "cloud-sql-proxy" {{- else if .Values.global.useCombinedDb }} "combined-db" {{- else }} "tenant-db" {{- end }}
