apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: {{ .Values.replicas }} # default 1 in the values file
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: opa
    spec:
{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") .Values.global.enablePriorityClass }}
      priorityClassName: magda-8
{{- end }}
      containers:
      - name: opa
        image: openpolicyagent/opa:0.17.1
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/opa-data/policies"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8181
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - readOnly: true
          mountPath: /opa-data
          name: opa-policies-volume
      volumes:
        - name: opa-policies-volume
          configMap:
            name: opa-policies
            items:
            {{- range $path, $bytes := .Files.Glob "policies/**/*" }}
            - key: {{ base $path }}
              path: {{ dir $path }}/{{ base $path }}
            {{- end }}
