global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: https://dev.magda.io
  image:
    pullPolicy: Always
  rollingUpdate:
    maxUnavailable: 1
  enablePriorityClass: true
  defaultContactEmail: "magda-test@googlegroups.com"
  enableMultiTenants: false
  connectors:
    includeInitialJobs: false
    includeCronJobs: true
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  minions:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false

tags:
  all: true
  ingress: true
  connectors: true
  minion-broken-link: true
  minion-linked-data-rating: true
  minion-visualization: true
  minion-format: true

magda-core:
  ingress:
    hostname: dev.magda.io
    ingressClass: nginx
    enableTls: true
    domains:
      - dev.magda.io
      - "*.dev.magda.io"

  gateway:
    enableCkanRedirection: false
    enableAuthEndpoint: true
    enableHttpsRedirection: true
    auth:
      facebookClientId: "173073926555600"
      arcgisClientId: "d0MgVUbbg5Z6vmWo"
      googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
      ckanAuthenticationUrl: https://data.gov.au/data
      vanguardWsFedIdpUrl: https://thirdparty.authentication.business.gov.au/fas/v2/wsfed12/authenticate
      vanguardWsFedRealm: https://environment.magda.io/integration-test-2
    cors:
      credentials: true
      origin: true
    helmet:
      frameguard: false
    csp:
      directives:
        scriptSrc:
          - "''self''"
          - browser-update.org
          - "''unsafe-inline''"
        objectSrc:
          - "''none''"
        reportUri: https://sdga.report-uri.com/r/d/csp/enforce

  combined-db:
    waleBackup:
      method: WAL
      gsPrefix: "gs://magda-postgres-backups-asia/dev"
      executionTime: 03:00
      googleApplicationCreds:
        secretName: storage-account-credentials
        fileName: TerriaJS-5e042b649f8a.json
    data:
      storage: 250Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: DoesNotExist

  elasticsearch:
    data:
      heapSize: 500m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
    backup:
      googleApplicationCreds:
        secretName: storage-account-credentials
        fileName: db-service-account-private-key.json

  indexer:
    readSnapshots: false
    makeSnapshots: false
    elasticsearch:
      useGcsSnapshots: true
      gcsSnapshotBucket: "magda-es-snapshots-dev"
      gcsSnapshotClient: "default"

  web-server:
    fallbackUrl: "https://data.gov.au"
    showNotificationBanner: false
    featureFlags:
      cataloguing: true
    vocabularyApiEndpoints:
      - "https://vocabs.ands.org.au/repository/api/lda/abares/australian-land-use-and-management-classification/version-8/concept.json"
      - "https://vocabs.ands.org.au/repository/api/lda/neii/australian-landscape-water-balance/version-1/concept.json"
      - "https://vocabs.ands.org.au/repository/api/lda/ands-nc/controlled-vocabulary-for-resource-type-genres/version-1-1/concept.json"

  correspondence-api:
    alwaysSendToDefaultRecipient: true
    smtpHostname: "smtp.mailgun.org"
    smtpPort: 2525

minion-broken-link:
  domainWaitTimeConfig:
    data.csiro.au: 5
    data.gov.au: 5
    data.act.gov.au: 30

# Connectors settings is built in Magda chart value file but you can override as the followings:
# e.g. dga connector:
# connector-dga:
#   config:
#     id: dga
#     name: "data.gov.au"
#     sourceUrl: "https://data.gov.au/data/"
#     pageSize: 1000
#     ignoreHarvestSources: ["*"]