apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: {{- if .Values.production }} "client" {{- else }} "data" {{- end }}
spec:
  selector:
    component: elasticsearch
    role: {{- if .Values.production }} "client" {{- else }} "data" {{- end }}
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
