apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    role: {{- if .Values.production }} "master" {{- else }} "data" {{- end }}
spec:
  selector:
    component: elasticsearch
    role: {{- if .Values.production }} "master" {{- else }} "data" {{- end }}
  ports:
  - name: transport
    port: 9300
    protocol: TCP
