{{ if and .Values.autoscaler.enabled .Values.deployments.readOnly.enable }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: registry-api-read-only
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: registry-api-read-only
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}
{{ end }}
